name: Feature request
description: Suggest a feature for SvgChunkWebpackPlugin
labels: 'feature'
body:
  - type: textarea
    attributes:
      label: If the feature solves a problem you have, specify it here.
      description: A description of what the problem is.
      placeholder: Ex. I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the proposed feature.
      description: A description of what you want to happen. Be as specific as possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here. Also if you have any PRs related to this issue that are already open that you would like us to look at.
  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would make my life easier
        - I cannot use Costro without it
    validations:
      required: true
